sudo: required
language: node_js
node_js: '8'
git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn && yarn test
before_deploy:
- printf "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}\n" >> ~/.npmrc
deploy:
  provider: script
  script: yarn run publish:next
  skip_cleanup: true
  on:
    branch: master
